### ISSUE TITLE
Account not being added to the switcher

### ISSUE THREAD

**Issue by zjavierf** [symonxdd/epic-games-account-switcher#1]
I've added my first account and I'm trying to add 2 others but it doesn't detect when I've logged into the other account. I've tried using the scan feature in the settings but nothing. Can I get a video or list of instructions on how to properly add accounts to the switcher?

EDIT: I reinstalled the switcher and know I can't add accounts at all. Can i get a tutorial on how to use this?

**Comment by zjavierf** [comment]
nvm somehow got it working

**Comment by symonxdd** [comment]
I appreciate you reaching out!
If I understand you well, the issue might be that after logging into each additional account in the Epic Games launcher, the tool does not register these additional accounts, **because you don't open (and if opened, activate / put on the foreground) the tool again so it can register this additional account.** And it might be necessary to have the main 'Accounts' tab active in the tool; either have it active and add an additional account, then open the tool again. Or if you were in the Settings tab for example, just click on 'Accounts' when you open the tool back up after adding an additional account.

So I suggest you trying this out. I thought about implementing an auto-detect feature, but couldn't really find an optimal way to do this as some kind of background task constantly running in the background would be necessary. So either I'll reconsider this, or add an important note about this extra step!

You also mentioned that after a reinstallation the tool then won't register any accounts. Could you elaborate on this? Did you use the uninstaller found in the installation folder?

**Comment by unknownjwly** [comment]
Yes I'll elaborate. So after i uninstalled using the uninstaller found in the directory of the switcher and then reinstalled it, whenever I try repeating the same steps of adding an account nothing happens and nothing gets added. I've tried both running the switcher and epic games launcher in administrator mode but still haven't figured out how to do it. I will try the way you've explained it. Thanks for the reply

EDIT: I'm able to add my first account using these steps:

1) Log into Epic Games
2) Open switcher, go to settings and pressing scan
3) Go to accounts tab and click anywhere on open space
4) The application does 'Not Responding' for a second then account is added

I tried repeating those same steps for the next account I want to add but nothing

EDIT again: I tried redoing those steps to confirm that it works and it infact doesn't.

**Comment by symonxdd** [comment]
Ah! I think I know the issue now! Instead of doing your mentioned steps for adding an additional account, try following these:
1. Be logged into the Epic Games launcher (any account, or in your case the account which is already registered in the Switcher)
2. Go to the 'Manage' tab (under 'Accounts' tab)
3. Here, click on the 'Add' button found at the top under the 'Add new login' section
4. Next, click on the 'Add new login' button that appears in the flyout menu
5. Login into your other account in the Epic Games launcher
6. After successful login, go back to the Switcher and go to the 'Accounts' tab again, the additional account should appear in the list
7. (Repeat for additional accounts)

From what I understand in your case is that you did not use the 'Add' button in the 'Manage' tab, would I be correct?

PS: The Scan feature in Settings isn't for adding or registering accounts. Instead, it finds usernames linked to Epic Games User IDs in the logs generated by the Epic Games launcher.
This happens already on first launch of the Switcher and should only really be used if one or more of the added accounts in the Switcher don't show as the actual username but rather that account's user ID. So this could also be used in case you change the name of the account (though I'm aware of a bug where this might not yet work).

Please report back if the provided steps won't work!

**Comment by unknownjwly** [comment]
Apologies for late reply, but after 3-4 tries I found no luck. I'm not sure what I'm doing wrong here. And last time I did use the "Add new login" button in the flyout menu.

**Comment by symonxdd** [comment]
This is really strange, are you down to have a short screen share call so I can see live what's happening?

**Comment by unknownjwly** [comment]
Hey, I was able to get this working finally by properly running it in administrator mode for both the switcher and epic games. Turns out I didn't properly run them in administrator mode and that did it for me. Thanks for all the help.

**Comment by symonxdd** [comment]
I'm glad you got it working!

**Comment by symonxdd** [comment]
Hey again! I hope you’re doing well!
I’ve been working on an upgraded version of Epic Switcher that’s faster and improved overall. You can find it here: https://github.com/symonxdd/epic-switcher.

Would love to hear what you think if you get a chance to try it!
